name: 'Java Build and Test Action'
description: 'Custom GitHub Action to build Java projects and run tests with cache support'
author: 'Your Name'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  maven_cache_key:
    description: 'Cache key for Maven dependencies'
    required: true
    default: 'maven-dependencies'
outputs:
  test_results: 
    description: 'Result of the test run'

branding:
  icon: 'package'
  color: 'blue'
