name: "Build Java Project"
description: "Builds a Java project using Maven and caches dependencies"
inputs:
  java_version:
    description: "Java version to use"
    required: true
    default: "22"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java_version }}

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Upload jar as artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-jar
        path: target/*.jar
