name: Reusable Java Build Workflow

on:
  workflow_call:
    inputs:
      maven_cache_key:
        description: 'Cache key for Maven dependencies'
        required: true
        type: string
      APPNAME:
        description: 'Application name to use for Docker image'
        required: true
        type: string
      SKIPTEST:
        description: 'Skip tests during Maven build'
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Restore Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ inputs.maven_cache_key }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: |
          if [ "${{ inputs.SKIPTEST }}" = "true" ]; then
            mvn clean install -DskipTests=true
          else
            mvn clean install
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: target
          path: target

  docker-build:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: target

      - name: List folder structure
        run: ls -l

      - name: Docker build
        run: |
          docker build -t ${{ inputs.APPNAME }}:latest .
