name: Reusable Java Build Workflow

on:
  workflow_call:
    inputs:
      maven_cache_key:
        description: 'Cache key for Maven dependencies'
        required: true
        type: string
      APPNAME:
        description: 'Application name to use for Docker image'
        required: true
        type: string
      SKIPTEST:
        description: 'Skip tests during Maven build'
        required: false
        default: 'true'
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Restore Maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ inputs.maven_cache_key }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: |
          if [ "${{ inputs.skip_tests }}" = "true" ]; then
            mvn clean install -DskipTests=true
          else
            mvn clean install
          fi

  docker-build:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker build
        run: |
          docker build -t ${{ inputs.APPNAME }}:latest .
