name: Reusable Deployment to Google Cloud Run

on:
  workflow_call:
    inputs:
      APPNAME:
        description: 'Name of the application for deployment'
        required: true
        type: string
      IMAGE_TAG:
        description: 'Tag for the Docker image'
        required: true
        type: string
      REGION:
        description: 'Google Cloud Run region'
        required: true
        type: string
      CPU:
        description: 'Number of CPUs for each instance'
        required: false
        default: '1'
        type: string
      MEMORY:
        description: 'Memory limit for each instance'
        required: false
        default: '512Mi'
        type: string
      CONCURRENCY:
        description: 'Concurrency limit per instance'
        required: false
        default: '80'
        type: string
      MAX_INSTANCES:
        description: 'Maximum number of instances'
        required: false
        default: '10'
        type: string
      TIMEOUT:
        description: 'Timeout for each request'
        required: false
        default: '300s'
        type: string
    secrets:
      GCP_SA_KEY:
        required: true
      GCP_PROJECT_ID:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          gcloud run deploy ${{ inputs.APPNAME }} \
            --image gcr.io/$PROJECT_ID/${{ inputs.APPNAME }}:${{ inputs.IMAGE_TAG }} \
            --platform managed \
            --region ${{ inputs.REGION }} \
            --allow-unauthenticated \
            --cpu ${{ inputs.CPU }} \
            --memory ${{ inputs.MEMORY }} \
            --concurrency ${{ inputs.CONCURRENCY }} \
            --timeout ${{ inputs.TIMEOUT }} \
            --max-instances ${{ inputs.MAX_INSTANCES }}
